export const CATEGORY = {
    ALPHA: { name: 'ALPHABETS' },
    NUM: { name: 'NUMBERS' },
    ARROW: { name: 'ARROWS' },
    SMILEY: { name: 'SMILEYS' },
    REWARD: { name: 'REWARDS' },
    DECO: { name: 'DECO' },
    INDEX: { name: 'INDEX' },
    LABEL: { name: 'LABELS' },
}

export const PRODUCTS = [
    {
        title: 'ALPHA 01',
        subtitle: '9mm Circle Alphabets A-Z',
        price: 20,
        image: 'alpha01',
        category: CATEGORY.ALPHA,
        description: '',
    },
    {
        title: 'NUM 01',
        subtitle: '9mm Circle Numbers 1-100',
        price: 20,
        image: 'num01',
        category: CATEGORY.NUM,
        description: '',
    },
    {
        title: 'NUM 02',
        subtitle: '10mm Circle Numbers Glossy 1-100',
        price: 15,
        image: 'num02',
        category: CATEGORY.NUM,
        description: '',
    },
    {
        title: 'NUM 03',
        subtitle: '15mm Circle Numbers Glossy 1-100',
        price: 7,
        image: 'num03',
        category: CATEGORY.NUM,
        description: '',
    },
    {
        title: 'NUM 04',
        subtitle: '10mm Circle Numbers Matte 1-100',
        price: 14,
        image: 'num04',
        category: CATEGORY.NUM,
        description: '',
    },
    {
        title: 'NUM 05',
        subtitle: '15mm Circle Numbers Matte 1-100',
        price: 15,
        image: 'num05',
        category: CATEGORY.NUM,
        description: '',
    },
    {
        title: 'NUM 06',
        subtitle: 'Outline Circle Numbers 1-50',
        price: 1,
        image: 'num06',
        category: CATEGORY.NUM,
        description: '',
        variation: [
            {
                name: 'Red',
                image: 'num06',
            },
            {
                name: 'Orange',
                image: 'num06',
            },
        ],
    },
    {
        title: 'ARROW 01',
        subtitle: 'Fluorescent Arrow',
        price: 25,
        image: 'arrow01',
        category: CATEGORY.ARROW,
        description: '',
    },
    {
        title: 'ARROW 02',
        subtitle: 'Classic Arrow',
        price: 20,
        image: 'arrow02',
        category: CATEGORY.ARROW,
        description: '',
    },
    {
        title: 'ARROW 03',
        subtitle: 'Quads Arrow',
        price: 10,
        image: 'arrow03',
        category: CATEGORY.ARROW,
        description: '',
    },
    {
        title: 'SMILEY 01',
        subtitle: 'Fluorescent Smileys',
        price: 30,
        image: 'smiley01',
        category: CATEGORY.SMILEY,
        description: '',
    },
    {
        title: 'SMILEY 02',
        subtitle: 'Classic Smileys',
        price: 15,
        image: 'smiley02',
        category: CATEGORY.SMILEY,
        description: '',
    },
    {
        title: 'SMILEY 03',
        subtitle: 'Golden Smileys',
        price: 10,
        image: 'smiley03',
        category: CATEGORY.SMILEY,
        description: '',
    },
    {
        title: 'SMILEY 04',
        subtitle: 'Special Smileys',
        price: 2,
        image: 'smiley04',
        category: CATEGORY.SMILEY,
        description: '',
        variation: [
            {
                name: 'SMILEY 4.1',
                image: 'smiley04-i',
            },
            {
                name: 'SMILEY 4.2',
                image: 'smiley04-ii',
            },
            {
                name: 'SMILEY 4.3',
                image: 'smiley04-iii',
            },
            {
                name: 'SMILEY 4.4',
                image: 'smiley04-iv',
            },
        ],
    },
    {
        title: 'DECO 01',
        subtitle: 'Fluorescent Mix',
        price: 30,
        image: 'deco01',
        category: CATEGORY.DECO,
        description: '',
    },
    {
        title: 'DECO 02',
        subtitle: 'Classic Hearts',
        price: 5,
        image: 'deco02',
        category: CATEGORY.DECO,
        description: '',
    },
    {
        title: 'INDEX 01',
        subtitle: 'Colorful Index',
        price: 10,
        image: 'index01',
        category: CATEGORY.INDEX,
        description: '',
    },
    {
        title: 'INDEX 02',
        subtitle: 'Special Mix',
        price: 5,
        image: 'index02',
        category: CATEGORY.INDEX,
        description: '',
    },
    {
        title: 'LABEL 01',
        subtitle: 'Special Mix',
        price: 12,
        image: 'label01',
        category: CATEGORY.LABEL,
        description: '',
    },
    {
        title: 'LABEL 02',
        subtitle: 'Pastel & Fluorescent Tags',
        price: 10,
        image: 'label02',
        category: CATEGORY.LABEL,
        description: '',
    },
]
